--What is the total revenue generated by each sales representative?
-- Rationale: This provides insights into how sales representatives influence web activity and revenue generation.

SELECT sr.name AS sales_rep, SUM(o.total_amt_usd) AS total_revenue
FROM orders o
JOIN accounts a ON o.account_id = a.id
JOIN sales_reps sr ON a.sales_rep_id = sr.id
GROUP BY sr.name
ORDER BY total_revenue DESC;

--Which accounts have the most web interactions and their total purchase amount?
--Rationale: Identifying high-engagement accounts with large purchases can help target retention strategies.

SELECT a.id, a.name, COUNT(we.id) AS web_interactions, SUM(o.total_amt_usd) AS total_purchase
FROM web_events we
JOIN accounts a ON we.account_id = a.id
JOIN orders o ON a.id = o.account_id
GROUP BY a.id, a.name
ORDER BY total_purchase DESC;

--What is the average order value by sales representative?*
--Rationale: Understanding which sales reps are driving higher-value orders helps in performance evaluations and strategy adjustments.
   
SELECT sr.name AS sales_rep, AVG(o.total_amt_usd) AS avg_order_value
FROM orders o
JOIN accounts a ON o.account_id = a.id
JOIN sales_reps sr ON a.sales_rep_id = sr.id
GROUP BY sr.name
ORDER BY avg_order_value DESC;
 
--How has the number of web events changed yearly over time?*
--Rationale: Analyzing trends in events over time can identify peaks and troughs, highlighting periods of high activity.
   
SELECT DATE_TRUNC('year', occurred_at) AS event_year, COUNT(*) AS event_count
FROM web_events
GROUP BY event_year
ORDER BY event_year;  

--Which days of the week are the most active for web events?*
--Rationale: Knowing the most active days can help optimize marketing and support team schedules.
   

SELECT TO_CHAR(occurred_at, 'Day') AS day_of_week, COUNT(*) AS event_count
FROM web_events
GROUP BY day_of_week
ORDER BY event_count DESC;


--What is the distribution of web events by time of day?*
-- Rationale: Analyzing the time of day when events occur can help schedule content releases or support services.
    
SELECT EXTRACT(HOUR FROM occurred_at) AS hour_of_day, COUNT(*) AS event_count
FROM web_events
GROUP BY hour_of_day
ORDER BY hour_of_day;

--Total revenue by each paper type
--Rational: To identify the paper type with the highest sales
	
SELECT SUM(standard_amt_usd) AS standard_total_sales,
SUM(gloss_amt_usd) AS gloss_total_sales,
SUM(poster_amt_usd) AS poster_total_sales
FROM orders


-- Customer Lifetime Value?
--Rationale: To identify Which customers have placed the most orders

SELECT a.name, COUNT(o.total_amt_usd)
FROM accounts a
JOIN orders o
ON a.id = o.account_id
GROUP BY  a.name
ORDER BY COUNT(o.total_amt_usd) DESC

-- Customer Segmentation by region?
--Rationale: To analyze the total revenue generated by each region.
	
SELECT r.name, SUM(o.total_amt_usd) AS total_revenue
FROM accounts a
JOIN sales_reps s ON s.id = a.sales_rep_id
JOIN region r ON r.id = s.region_id
JOIN orders o ON a.id = o.account_id
GROUP BY r.name
ORDER BY total_revenue DESC;

--Total Revenue generated across each channel
--Rationale: To identify the channel with the highest total sales 
SELECT w.channel, SUM(DISTINCT o.total_amt_usd) AS total_revenue
FROM orders o
JOIN web_events w ON o.account_id = w.account_id
GROUP BY w.channel
ORDER BY total_revenue DESC;

